### ISSUE TITLE
Gunzip incoming requests

### ISSUE THREAD

**Issue by carlessistare** [gin-contrib/gzip#15]
Hello @appleboy I am responsible for an API developed with Gin and the incoming requests are gzip (Content-Encoding).
I realise (or I cannot find) any lib supporting this, so I need to gunzip incoming buffer before doing anything.
Would it be appropriate to do a PR into this project in order to automatically gunzip incoming bodies if Content-Encoding is set to "gzip"?

**Comment by appleboy** [comment]
PR Welcome :)

**Comment by appleboy** [comment]
@carlessistare Please see the #32
