### ISSUE TITLE
Possible memory leak

### ISSUE THREAD

**Issue by dev-mull** [gin-contrib/gzip#26]
I am not sure if this is a gzip or gin issue, but I will start here since it has to do with compression.

I have an api that is using the contrib/gzip lib, It is obviously running continuously.

After about a day the service crashes due to memory exhaustion on the host. 

Using pprof I see flate.NewWriter is using 90.05% of inuse_space. I have event forked this project and swapped stock gzip for klauspost

go version go1.11.1 linux/amd64

Time: Jun 20, 2019 at 1:28pm (CDT)
Showing nodes accounting for 20518.91MB, 97.75% of 20990.94MB total
Dropped 221 nodes (cum <= 104.95MB)
      flat  flat%   sum%        cum   cum%
17767.65MB 84.64% 84.64% 18902.19MB 90.05%  compress/flate.NewWriter
 1075.50MB  5.12% 89.77%  1134.55MB  5.40%  compress/flate.(*compressor).init

**Comment by AllenLyu** [comment]
have you found the reason cause this?

**Comment by sharepusher** [comment]
We experienced similar issue, we've no idea whether it's caused by increased GOGC, but it is a reason that make our system unstable and OOM. After we disable the gzip, all works well and the mem used is in a very low level.

**Comment by pranjalis17** [comment]
Hi @dev-mull I'm facing a similar issue. Did you find a fix for this?

**Comment by ben-swit** [comment]
i'm facing a similar issue

**Comment by ben-swit** [comment]
i solve this problem 

change package "github.com/klauspost/compress/gzip"

**Comment by csdgwei** [comment]
I'm facing a similar issue here when trying to add `GzipHandler` into Gin middleware using `apis.Use(gzip.Gzip(gzip.DefaultCompression))`. @niltooth is there a fix for this issue?
@ben-swit by "change package "github.com/klauspost/compress/gzip"", do you mean change the package from `compress/gzip` to `github.com/klauspost/compress/gzip` inside the the `gin-contrib/gzip` library?

**Comment by AndrewKostousov** [comment]
+1 here

To resolve memory leak issue I switched to [remerge/zip](https://github.com/remerge/gzip) fork of this package. It essentially does exactly this - replaces `compress/gzip` dependecy with `github.com/klauspost/compress/gzip`.

**Comment by ssksameer56** [comment]
Hi @AndrewKostousov ,
can you help me with how did you replace the package? gin-contrib is currently on v 0.0.6 while remerge isnt on it.

**Comment by AndrewKostousov** [comment]
With something like this in my go.mod:
```
require (
	github.com/gin-contrib/gzip v0.0.6
)

replace (
	github.com/gin-contrib/gzip => github.com/remerge/gzip v0.0.6-0.20220602083918-9c6d50f79583
)
```
