### ISSUE TITLE
ambiguous import `github.com/ugorji/go/codec`

### ISSUE THREAD

**Issue by Owen-igaw** [gin-contrib/gzip#30]
Hi. First of all, thanks for your efforts. : D

But, this package seems to make a package dependency crash with gin-gonic.

When I import the both of "github.com/gin-contrib/gzip" and "github.com/gin-contrib/static" and run these commands (`go mod vendor -v`, `go mod tidy`, `go run main.go` ), I got this errors below.

```
build command-line-arguments: cannot load github.com/ugorji/go/codec: ambiguous import: found github.com/ugorji/go/codec in multiple modules:
        github.com/ugorji/go v1.1.4 (C:\Go\MYGOPATH\pkg\mod\github.com\ugorji\go@v1.1.4\codec)
        github.com/ugorji/go/codec v0.0.0-20181022190402-e5e69e061d4f (C:\Go\MYGOPATH\pkg\mod\github.com\ugorji\go\codec@v0.0.0-20181022190402-e5e69e061d4f)
```

As a solution of this problem, I tried to add `replace github.com/ugorji/go => github.com/ugorji/go/codec v0.0.0-20181022190402-e5e69e061d4f`.
This solution makes my project works well, but I can't sure this is a good way for such problems.

Is this an error? If it is, what should I do to solve this?

Thanks for reading.

**Comment by thinkerou** [comment]
please post your go.mod

**Comment by Owen-igaw** [comment]
@thinkerou

```
module github.com/[...]

go 1.12

require (
	github.com/ashwanthkumar/slack-go-webhook v0.0.0-20181208062437-4a19b1a876b7
	github.com/aws/aws-sdk-go v1.21.0
	github.com/dgrijalva/jwt-go v3.2.0+incompatible
	github.com/elazarl/goproxy v0.0.0-20190421051319-9d40249d3c2f // indirect
	github.com/elazarl/goproxy/ext v0.0.0-20190421051319-9d40249d3c2f // indirect
	github.com/gin-contrib/gzip v0.0.1
	github.com/gin-contrib/static v0.0.0-20190511124741-c1cdf9c9ec7b
	github.com/gin-gonic/gin v1.4.0
	github.com/gomodule/redigo v2.0.0+incompatible
	github.com/jinzhu/gorm v1.9.7
	github.com/kr/pretty v0.1.0 // indirect
	github.com/moul/http2curl v1.0.0 // indirect
	github.com/parnurzeal/gorequest v0.2.15 // indirect
	github.com/pkg/errors v0.8.1 // indirect
	github.com/smartystreets/goconvey v0.0.0-20190330032615-68dc04aab96a // indirect
	golang.org/x/crypto v0.0.0-20190325154230-a5d413f7728c
)

replace github.com/ugorji/go => github.com/ugorji/go/codec v0.0.0-20181022190402-e5e69e061d4f
```

**Comment by Owen-igaw** [comment]
@thinkerou 
Oh, I just found a problem with that solution.

In that way, `go run` works find but `go build` fails with a error like below.

```
go: github.com/ugorji/go/codec@v0.0.0-20181022190402-e5e69e061d4f used for two different module paths (github.com/ugorji/go and github.com/ugorji/go/codec)
```

**Comment by Owen-igaw** [comment]
@thinkerou 

As another solution, I tried to replace the `ugorji/go`'s own version to `v1.1.7`. ( `ugorji` recommends to use this version for avoiding `ambiguous import` with `ugorji/go/codec` ( the `ugorji/go/codec` is treated different package with `ugorji/go`. And `ugorji` said this problem is solved  in this version.))

I wrote below line at end of go.mod (replace the `replace github.com/ugorji/go => github.com/ugorji/go/codec v0.0.0-20181022190402-e5e69e061d4f` line)
```
....
	golang.org/x/crypto v0.0.0-20190325154230-a5d413f7728c
)

replace github.com/ugorji/go => github.com/ugorji/go v1.1.7
```

Adding this line, both of  `go run` and `go build` seem to works fine!
But, I still can't sure that this way is good as module handling in golang.

It's a general way to solve this? Or, how should I do for this?

Thanks and sorry for lots of re-comment .. X(

**Comment by pyzworld** [comment]
me too 
-------
GOROOT=/usr/local/go #gosetup
GOPATH=/Users/pyzworld/go #gosetup
/usr/local/go/bin/go build -o /private/var/folders/h2/9kmqqvx5631093b0yrx5r4pm0000gn/T/___go_build_main_go "/Volumes/DATA One/workspaces/go/badloli/main.go" #gosetup
build command-line-arguments: cannot load github.com/ugorji/go/codec: ambiguous import: found github.com/ugorji/go/codec in multiple modules:
	github.com/ugorji/go v1.1.4 (/Users/pyzworld/go/pkg/mod/github.com/ugorji/go@v1.1.4/codec)
	github.com/ugorji/go/codec v0.0.0-20181022190402-e5e69e061d4f (/Users/pyzworld/go/pkg/mod/github.com/ugorji/go/codec@v0.0.0-20181022190402-e5e69e061d4f)


-------
go module
go 1.12

require (
	github.com/gin-contrib/gzip v0.0.1
	github.com/gin-gonic/gin v1.4.0
	github.com/go-redis/redis v6.15.3+incompatible
	github.com/go-stack/stack v1.8.0 // indirect
	github.com/golang/snappy v0.0.1 // indirect
	github.com/google/go-cmp v0.3.0 // indirect
	github.com/tidwall/pretty v1.0.0 // indirect
	github.com/xdg/scram v0.0.0-20180814205039-7eeb5667e42c // indirect
	github.com/xdg/stringprep v1.0.0 // indirect
	go.mongodb.org/mongo-driver v1.0.4
	golang.org/x/sync v0.0.0-20190423024810-112230192c58 // indirect
)

**Comment by Owen-igaw** [comment]
> ## me too
> GOROOT=/usr/local/go #gosetup
> GOPATH=/Users/pyzworld/go #gosetup
> /usr/local/go/bin/go build -o /private/var/folders/h2/9kmqqvx5631093b0yrx5r4pm0000gn/T/___go_build_main_go "/Volumes/DATA One/workspaces/go/badloli/main.go" #gosetup
> build command-line-arguments: cannot load github.com/ugorji/go/codec: ambiguous import: found github.com/ugorji/go/codec in multiple modules:
> github.com/ugorji/go v1.1.4 (/Users/pyzworld/go/pkg/mod/github.com/ugorji/go@v1.1.4/codec)
> github.com/ugorji/go/codec v0.0.0-20181022190402-e5e69e061d4f (/Users/pyzworld/go/pkg/mod/github.com/ugorji/go/codec@v0.0.0-20181022190402-e5e69e061d4f)
> 
> go module
> go 1.12
> 
> require (
> github.com/gin-contrib/gzip v0.0.1
> github.com/gin-gonic/gin v1.4.0
> github.com/go-redis/redis v6.15.3+incompatible
> github.com/go-stack/stack v1.8.0 // indirect
> github.com/golang/snappy v0.0.1 // indirect
> github.com/google/go-cmp v0.3.0 // indirect
> github.com/tidwall/pretty v1.0.0 // indirect
> github.com/xdg/scram v0.0.0-20180814205039-7eeb5667e42c // indirect
> github.com/xdg/stringprep v1.0.0 // indirect
> go.mongodb.org/mongo-driver v1.0.4
> golang.org/x/sync v0.0.0-20190423024810-112230192c58 // indirect
> )

Try to add this line after your require block.
`replace github.com/ugorji/go => github.com/ugorji/go v1.1.7`

**Comment by appleboy** [comment]
Add the following in go.mod

```
```

**Comment by appleboy** [comment]
Or upgrade `github.com/ugorji/go` to v1.1.7 version
