### ISSUE TITLE
Could you release a new version?

### ISSUE THREAD

**Issue by laszlocph** [gin-contrib/gzip#33]
Gin v1.4.0 works with master, but not with the tagged version. 

I got this error: https://github.com/gin-gonic/gin/issues/1673

**Comment by pdhinwa** [comment]
Yes, please release a new version of this lib. We want to use newly added features.

**Comment by snowdream** [comment]
please release a new version.

**Comment by appleboy** [comment]
https://github.com/gin-contrib/gzip/releases/tag/v0.0.2
