### ISSUE TITLE
Using GZIP with gin DataFromReader is not behaving correctly

### ISSUE THREAD

**Issue by uppalabharath** [gin-contrib/gzip#39]
I have a requirement where upon clicking a link the file gets downloaded. As the file may be large I use gin's DataFromReader so that the download can happen in chunks. But when the gzip compression is enabled, the file is getting corrupted and chrome shows some error like network error. I disabled the gzip middleware and it worked normally. 

Any pointers on where to look or some configuration needs to be done for handling this correctly. Please advise.

**Comment by uppalabharath** [comment]
I think this PR https://github.com/gin-contrib/gzip/pull/27 relates to the problem I am facing. @appleboy Could you please review and do the merge if the changes look good and release a new tag.. 

Thanks

**Comment by appleboy** [comment]
@uppalabharath I will take it.

**Comment by appleboy** [comment]
bump to v0.0.3 https://github.com/gin-contrib/gzip/releases/tag/v0.0.3

**Comment by uppalabharath** [comment]
Thanks @appleboy for quick action on this and thanks @segevfiner for the fix..
