### ISSUE TITLE
Snyk vulnerability HTTP Response Splitting on older version of github.com/gin-gonic/gin

### ISSUE THREAD

**Issue by ruchi-dhore-tw** [gin-contrib/gzip#61]
We are using the latest version of github.com/gin-contrib/gzip@v0.0.5 which internally uses the gin-gonic library and the version is github.com/gin-gonic/gin@v1.7.4 in go.mod

This has introduced snyk vulnerability HTTP Response Splitting with the following path:
Introduced through: our-repo@0.0.0 › github.com/gin-contrib/gzip@v0.0.5 › github.com/gin-gonic/gin@v1.7.4

Snyk link issue: https://security.snyk.io/vuln/SNYK-GOLANG-GITHUBCOMGINGONICGIN-1041736

In master branch in go.mod, I see gin-gonic version has been upgraded to v1.8.1

What is the estimated date to release this master branch changes?

**Comment by ruchi-dhore-tw** [comment]
@appleboy @thinkerou @mkfsn can you have a look at this?

**Comment by thinkerou** [comment]
@ruchi-dhore-tw please upgrade to v0.0.6, thanks!

**Comment by ruchi-dhore-tw** [comment]
Thank you @thinkerou
