### ISSUE TITLE
go.mod: upgrade dependency github.com/gin-contrib/gzip to latest version to avoid vulnerability

### ISSUE THREAD

**Issue by mswathi-tw** [gin-contrib/gzip#64]
We are using the latest version (github.com/gin-contrib/gzip@v0.0.5) which internally uses the following library

github.com/gin-contrib/gzip@v0.0.5 › github.com/gin-gonic/gin@v1.7.4

This has introduced certain snyk vulnerability **HTTP Response Splitting** and in order to solve this issue following library version has to be upgraded to github.com/gin-gonic/gin@1.7.7 or more.

Can you please upgrade it.

**Comment by thinkerou** [comment]
@mswathi-tw please upgrade to v0.0.6, thanks!

**Comment by mswathi-tw** [comment]
Thanks!!
